/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankingsystem;

public class Main {
    public static void main(String[] args) {
        String fileName = "card.s3db";

        Application app = new Application(fileName);
        app.run();
    }
}
